name: Deploy cyf-cloud.back

on:
    push:
        branches:
            - master
        paths-ignore:
            - README.md

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Pull and redeploy
              uses: garygrossgarten/github-action-ssh@release
              with:
                  command: |
                      whoami
                      bash ${{ secrets.SCRIPT }}
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PSWD }}
                  port: ${{ secrets.PORT }}
