name: Deploy cyf-cloud.back

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull and redeploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            whoami
            cd ~/.web/cyf-cloud.back/
            git pull

            # 修改配置文件为部署配置文件
            mv ./server.cfg ./server_dev.cfg
            mv ./server_dep.cfg ./server.cfg

            # 重新启动服务器
            if ! screen -list | grep -q "go"; then
              screen -dmS go bash -c "cd ~/.web/cyf-cloud.back/; go run ./main.go; bash"
            else
              screen -S go -p 0 -X stuff "^C"
              screen -S go -p 0 -X stuff "cd ~/.web/cyf-cloud.back/^M"
              screen -S go -p 0 -X stuff "go run ./main.go^M"
            fi
          host: cn-xz-bgp.sakurafrp.com
          username: cyf
          password: ${{ secrets.PSWD }}
          port: 13631